name: Docker Image CI

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }} # Solo il nome del repository (spiderweb)

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
        packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Read version from file and adjust tag if development branch
      id: set_image_tag
      run: |
        VERSION=$(cat static/version.txt)
        if [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
          VERSION="${VERSION}_dev"
        fi
        echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV
        echo "IMAGE_TAG=$VERSION" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }}
        docker push ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }}
        echo "Image pushed to ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }}"

    - name: Echo pushed image (optional)
      run: |
        echo "Docker image pushed on: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }}"