
on:
  push:
    branches:
      - master  

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from file
        id: version
        run: |
          if [ ! -f cfg/version.txt ]; then 
            echo "Error: version.txt not found!" && exit 1
          fi
          echo "VERSION=$(cat cfg/version.txt)" >> $GITHUB_ENV
                
      - name: Debug Version Output
        run: echo "Read version: ${VERSION}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: "New automatic release generated."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

